-- =========================================================
-- MOTIVA - Sprint 3 - Dados de teste
-- =========================================================

-- Equipes
INSERT INTO TB_EQUIPE_MANUTENCAO (ID, NOME, ESPECIALIDADE, QTD_MEMBROS, DISPONIVEL)
VALUES (SEQ_EQUIPE.NEXTVAL, 'Equipe Norte', 'ROCADA', 5, 'S');

INSERT INTO TB_EQUIPE_MANUTENCAO (ID, NOME, ESPECIALIDADE, QTD_MEMBROS, DISPONIVEL)
VALUES (SEQ_EQUIPE.NEXTVAL, 'Equipe Sul', 'PULVERIZACAO', 4, 'S');

INSERT INTO TB_EQUIPE_MANUTENCAO (ID, NOME, ESPECIALIDADE, QTD_MEMBROS, DISPONIVEL)
VALUES (SEQ_EQUIPE.NEXTVAL, 'Equipe Mista Central', 'MISTA', 8, 'N');

-- Trechos de rodovia
INSERT INTO TB_TRECHO_RODOVIA (ID, TITULO, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO_CM, POSSUI_IOT)
VALUES (SEQ_TRECHO.NEXTVAL, 'Rodovia Anhanguera KM 10-15', 10, 15, 12, 'S');

INSERT INTO TB_TRECHO_RODOVIA (ID, TITULO, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO_CM, POSSUI_IOT)
VALUES (SEQ_TRECHO.NEXTVAL, 'Rodovia Bandeirantes KM 40-45', 40, 45, 35, 'N');

INSERT INTO TB_TRECHO_RODOVIA (ID, TITULO, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO_CM, POSSUI_IOT)
VALUES (SEQ_TRECHO.NEXTVAL, 'Rodovia Castello Branco KM 60-65', 60, 65, 55, 'S');

INSERT INTO TB_TRECHO_RODOVIA (ID, TITULO, KM_INICIAL, KM_FINAL, NIVEL_VEGETACAO_CM, POSSUI_IOT)
VALUES (SEQ_TRECHO.NEXTVAL, 'Rodovia Dutra KM 100-105', 100, 105, 8, 'N');

-- Intervenções (associadas aos trechos/equipes acima - ajuste os IDs se necessário)
INSERT INTO TB_INTERVENCAO_OPERACIONAL (ID, TIPO, DESCRICAO, EXTENSAO_KM, ID_TRECHO, ID_EQUIPE)
VALUES (SEQ_INTERVENCAO.NEXTVAL, 'ROCADA', 'Roçada no trecho Anhanguera', 5, 1, 1);

INSERT INTO TB_INTERVENCAO_OPERACIONAL (ID, TIPO, DESCRICAO, EXTENSAO_KM, ID_TRECHO, ID_EQUIPE)
VALUES (SEQ_INTERVENCAO.NEXTVAL, 'PULVERIZACAO', 'Pulverização no trecho Castello Branco', 5, 3, 2);

COMMIT;
